#!/bin/bash
set -euo pipefail

file="./syntastica-parsers-gitdep/Cargo.toml"
raw="$(cat "$file")"
header="
###########################################
### All following code is autogenerated ###
### by running \`cargo xtask codegen\` in ###
### the syntastica workspace. #############
###########################################
"
echo -n "${raw//"$header"*/"$header"}" > "$file"

# Fetch and patch tree-sitter v0.26.8 for the emscripten duplicate-symbol fix.
# Upstream's `lib/binding_rust/build.rs::configure_wasm_build` fires for any
# `wasm32-unknown-*` target, colliding with emscripten's own libc. The workspace
# Cargo.toml has a `[patch.crates-io]` pointing at ./ignored/tree-sitter-patched.
patched_dir="./ignored/tree-sitter-patched"
if [ ! -d "$patched_dir/.git" ]; then
    mkdir -p "$(dirname "$patched_dir")"
    git clone --depth 1 --branch v0.26.8 https://github.com/tree-sitter/tree-sitter "$patched_dir"
fi

build_rs="$patched_dir/lib/binding_rust/build.rs"
if grep -q 'target.starts_with("wasm32-unknown")' "$build_rs"; then
    sed -i 's|target\.starts_with("wasm32-unknown")|target == "wasm32-unknown-unknown"|' "$build_rs"
fi
